### ISSUE TITLE
Meeting minutes

### ISSUE THREAD

**Issue by JasonICTSE** [SujanRaj20/INF2001-P4-3#11]
Meeting minutes QnA

**Comment by JasonICTSE** [comment]
![Image](https://github.com/SujanRaj20/INF2001-P4-3/assets/112858977/595d68a4-589a-49c7-afc3-492e41f75fb3)



![Image](https://github.com/SujanRaj20/INF2001-P4-3/assets/112858977/6734f62f-37f4-4e28-8b9e-bcf403083176)



![Image](https://github.com/SujanRaj20/INF2001-P4-3/assets/112858977/31362731-6d8b-444e-acd4-1151c204f6c2)

**Comment by hexluna** [comment]
Reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by minvee** [comment]
Reviewed

**Comment by ColdRainyDay365** [comment]
Reviewed

**Comment by NekoCoaster** [comment]
Reviewed

**Comment by JasonICTSE** [comment]
Closed as completed.
