### ISSUE TITLE
1.1.1 Define Product Scope

### ISSUE THREAD

**Issue by NekoCoaster** [SujanRaj20/INF2001-P4-3#12]
Task ID: # 1.1.1

The task is about coming up with a short description of the software scope, it's boundaries and it's purpose including relevant benefits, objectives and goals. 

The goal is to write 1-2 paragraphs describing the scope of the product while making sure to describe the benefits associated with the product.

The completion criteria is to ensure that a short description of the software scope, boundaries, purpose is clearly stated in the report. Any associated relevant benefits, objectives and goals must also be clearly stated in the report.

The allocation time is 2 days.

The start date of this task is 28 August 2023 and the end date is 29 August 2023.

The owner of the task is Jason Tan.

The status of the task is "Completed".

The priority of the task is high.

**Comment by Amabellzq** [comment]
Completed, Ready for review

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by NekoCoaster** [comment]
Reviewed.

**Comment by hexluna** [comment]
Reviewed

**Comment by minvee** [comment]
Reviewed

**Comment by NekoCoaster** [comment]
Closed as completed.
