### ISSUE TITLE
1.1.2 Related Background Literature

### ISSUE THREAD

**Issue by NekoCoaster** [SujanRaj20/INF2001-P4-3#13]
Task ID: #13

The objective of this task is to compile comprehensive research on the project's domain. This research should encompass relevant materials, methodologies, and existing software or APIs that can contribute to or compete with the project's goals.

The completion criteria involve the creation of a document that summarizes the key findings from the research. This document should serve as a valuable resource for the project team, providing insights into the domain's landscape and potential directions for the project.

The allocation time for this task is 2 days.

The task will commence on 29 August 2023 and conclude on 30 August 2023.

The task owner is Jason Tan.

The task status is "Completed".

The priority of the task is high.

**Comment by JasonICTSE** [comment]
Completed, Ready for review

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by hexluna** [comment]
Reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by minvee** [comment]
Reviewed

**Comment by Amabellzq** [comment]
Reviewed

**Comment by NekoCoaster** [comment]
Reviewed.

**Comment by NekoCoaster** [comment]
Closed as completed.
