### ISSUE TITLE
1.1.4 References and Acknowledgements

### ISSUE THREAD

**Issue by NekoCoaster** [SujanRaj20/INF2001-P4-3#15]
Task ID: #15

The Task is about listing any other documents or web addresses referenced in the report. These references may include user interface style guides, contracts, standards, system requirements specifications, use case documents, or a vision and scope document.

The goal is to compile a comprehensive list of all the documents and web addresses mentioned in the report. This list will provide easy access to additional resources that can enhance the understanding and context of the report's content.

The completion criteria are met when a document is created that includes all relevant references, categorized and hyperlinked where applicable, making it easy for readers to access additional information.

The allocated time for this task is 2 days.

The start date of this task is 1 Sep 2023, and the end date is 4 Sep 2023.

The owner of the task is Amabel Lim Zi Qin.

The status of the task is "Completed."

The priority of the task is **high**.

**Comment by Amabellzq** [comment]
Completed, Ready for review

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by minvee** [comment]
Reviewed

**Comment by hexluna** [comment]
reviewed

**Comment by NekoCoaster** [comment]
Reviewed.

**Comment by NekoCoaster** [comment]
Closed as completed.
