### ISSUE TITLE
1.2.2 Product Functionality

### ISSUE THREAD

**Issue by NekoCoaster** [SujanRaj20/INF2001-P4-3#17]
Task ID: #17

The Task is about summarizing the major functions that the product must perform or enable users to perform. These functions should be presented at a high-level, with detailed information to be provided in Section 3 of the report. This summary serves as an overview of the product's primary functions and can be based on the information outlined in the project description.

The goal is to create a concise yet informative summary of the product's major functions. This summary should give readers a clear understanding of what the product is expected to do without delving into the finer details, which will be covered in the subsequent section of the report.

The completion criteria are met when a well-structured summary of the product's major functions is provided. It should be easy for readers to grasp the essential functions that the product is designed to perform.

The allocated time for this task is 2 days.

The start date of this task is 4 September 2023, and the end date is 5 September 2023.

The owner of the task is Sureshbabu Sujanraj.

The status of the task is "Completed."

The priority of the task is **high**.

**Comment by NekoCoaster** [comment]
Bulleted list of all the overall functions of the system can be like:
**PF1:** The product shall ...
**PF2:** The product shall ...

**Comment by ColdRainyDay365** [comment]
Completed, ready for review

**Comment by hexluna** [comment]
Reviewed

**Comment by Amabellzq** [comment]
Reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by minvee** [comment]
reviewed

**Comment by NekoCoaster** [comment]
Reviewed.

**Comment by NekoCoaster** [comment]
Closed as completed.
