### ISSUE TITLE
1.2.3 Assumptions and Dependencies

### ISSUE THREAD

**Issue by NekoCoaster** [SujanRaj20/INF2001-P4-3#18]
Task ID: #18

The Task is about listing and detailing the assumed factors that could potentially impact the requirements outlined in the report. These assumptions are distinct from known facts and may include factors such as the use of third-party or commercial components, considerations related to the development or operating environment, and any constraints that could influence the project's success. Additionally, it's essential to identify any dependencies the project has on external factors, like reusing software components from other projects.

The goal is to compile a concise yet comprehensive list of major assumptions that have the potential to significantly affect the design and requirements of the project. These assumptions should be clearly stated and their potential impact on the project's success should be outlined.

The completion criteria are met when a list of significant assumptions and dependencies is provided, along with a brief description of each and their potential impact on the project's requirements and design.

The allocated time for this task is 2 days.

The start date of this task is 5 September 2023, and the end date is 6 September 2023.

The owner of the task is Sureshbabu Sujanraj.

The status of the task is "Completed."

The priority of the task is **high**.

**Comment by NekoCoaster** [comment]
TO DO: Provide a short list of some major assumptions that might significantly affect the design

**Comment by ColdRainyDay365** [comment]
Completed, ready for review

**Comment by hexluna** [comment]
Reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by Amabellzq** [comment]
Reviewed

**Comment by minvee** [comment]
Reviewed

**Comment by NekoCoaster** [comment]
Reviewed.

**Comment by NekoCoaster** [comment]
Closed as completed.
