### ISSUE TITLE
1.3.1 User Interface Requirements

### ISSUE THREAD

**Issue by NekoCoaster** [SujanRaj20/INF2001-P4-3#19]
Task ID: #19

The Task is about describing the logical characteristics of each interface between the software product and the users, focusing specifically on the main thermostat and not the mobile app. This description should be based on the graphic provided in the project description, serving as the foundation for understanding the user interface.

The goal is to provide a detailed description of the logical characteristics of the main thermostat's interface with users. This includes aspects such as user interactions, input methods, and the overall user experience. By elucidating these characteristics, the report aims to offer a clear understanding of how users will interact with the thermostat.

The completion criteria are met when a comprehensive description of the logical characteristics of the main thermostat's interface is provided. This description should cover key aspects of the user interface, including user interactions and input methods.

The allocated time for this task is 2 days.

The start date of this task is 6 September 2023, and the end date is 7 September 2023.

The owner of the task is Chong Ying Ee.

The status of the task is "Completed."

The priority of the task is **high**.

**Comment by NekoCoaster** [comment]
TO DO: Provide a short list of some major assumptions that might significantly affect the design

**Comment by hexluna** [comment]
User interface requirements interviewed with client
Completed the task. Ready for review.

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by minvee** [comment]
reviewed

**Comment by NekoCoaster** [comment]
Reviewed.

**Comment by NekoCoaster** [comment]
Closed as completed.
