### ISSUE TITLE
1.3.2 Functional Requirements

### ISSUE THREAD

**Issue by NekoCoaster** [SujanRaj20/INF2001-P4-3#20]
Task ID: #20

The Task is about specifying the detailed functional requirements of the system, which encompass the intended behavior, services, tasks, or functions that the system is expected to perform. This section builds upon the general functional requirements outlined in Section 2.2, providing a comprehensive list of specific functional requirements that materialize the product's functionality.

The goal is to create a detailed list of specific functional requirements that align with the product's intended behavior. Each requirement should be clearly defined, starting with a prefix (e.g., FR1, FR2) and a concise description of the system's expected behavior.

The completion criteria are met when a well-organized list of specific functional requirements is presented. Each requirement should be uniquely identified, thoroughly described, and directly linked to the product's intended behavior.

The allocated time for this task is 2 days.

The start date of this task is 7 September 2023, and the end date is 8 September 2023.

The owner of the task is Chong Ying Ee.

The status of the task is "Completed."

The priority of the task is **high**.

**Comment by NekoCoaster** [comment]
These are the specific functional requirements to materialize the Product Functionality in section 2.2.
Examples:
**FR1:** The system shall ...
**FR2:** The system shall ...

**Comment by hexluna** [comment]
FR1 to 16 Done
Completed the task, Ready for review

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by minvee** [comment]
Reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by NekoCoaster** [comment]
Reviewed.

**Comment by NekoCoaster** [comment]
Closed as completed.
