### ISSUE TITLE
1.3.3 Use Case Model

### ISSUE THREAD

**Issue by NekoCoaster** [SujanRaj20/INF2001-P4-3#21]
Task ID: #21

The Task is about creating and explaining a Use Case model and diagram to enhance the understanding of key concepts within the project. Specifically, the use case descriptions will be placed in Appendix A of the report. It is important to guide readers on where to locate the use case descriptions to ensure easy access to this valuable information.

The goal is to develop a clear and informative Use Case model and diagram that aids in explaining the project's concepts. Additionally, it involves providing clear instructions to readers regarding the location of the use case descriptions, which will be found in Appendix A.

The completion criteria are met when a well-structured Use Case model and diagram are presented, accompanied by clear guidance to inform readers that the use case descriptions can be found in Appendix A of the report.

The allocated time for this task is 3 days.

The start date of this task is 8 September 2023, and the end date is 12 September 2023.

The owner of the task is Jason Tan.

The status of the task is "Completed."

The priority of the task is **high**.

**Comment by JasonICTSE** [comment]
Completed, Ready for review

**Comment by hexluna** [comment]
Reviewed

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by minvee** [comment]
Reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by NekoCoaster** [comment]
Reviewed.

**Comment by NekoCoaster** [comment]
Closed as completed.
