### ISSUE TITLE
1.3.4 Non-functional Requirements

### ISSUE THREAD

**Issue by NekoCoaster** [SujanRaj20/INF2001-P4-3#22]
Task ID: #22

The Task is about incorporating generic non-functional requirements into the project documentation. This involves summarizing and listing a set of generic non-functional requirements that the system must adhere to.

The goal is to compile a comprehensive list of generic non-functional requirements that the system should meet. Each requirement should be clearly stated, starting with a prefix (e.g., NFR1, NFR2), and summarized succinctly to provide an overview of the non-functional aspects the system needs to address.

The completion criteria are met when a well-organized list of generic non-functional requirements is presented. Each requirement should be uniquely identified, concisely described, and included as part of the project documentation.

The allocated time for this task is 2 days.

The start date of this task is 12 September 2023, and the end date is 13 September 2023.

The owner of the task is Tan Yu.

The status of the task is "Completed."

The priority of the task is **high**.

**Comment by NekoCoaster** [comment]
Examples:
**NFR1:** The system shall provide the feature to present content in multi-lingual.
**NFR2:** The system shall …

**Comment by NekoCoaster** [comment]
Completed. Ready for review.

**Comment by hexluna** [comment]
Reviewed

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by minvee** [comment]
Reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by NekoCoaster** [comment]
Closed as completed.
