### ISSUE TITLE
1.3.4.1 Performance Requirements 

### ISSUE THREAD

**Issue by NekoCoaster** [SujanRaj20/INF2001-P4-3#23]
Task ID: #23

The Task is about defining performance requirements for the product under various circumstances and providing a rationale for these requirements. This involves specifying the timing relationships, especially for real-time systems, and making performance requirements as specific as possible. It's essential to help developers understand the intended performance characteristics and make appropriate design choices. Performance requirements may need to be stated for individual functional requirements or features as necessary.

The goal is to establish clear and specific performance requirements for the product based on the information gathered from the client or professor. Each requirement should be well-documented, starting with a prefix (e.g., NFR3, NFR4), and should include a rationale explaining the necessity of that particular performance requirement.

The completion criteria are met when a detailed list of performance requirements is provided, along with a clear rationale for each requirement. These requirements should be specific and tailored to the product's functionality and context.

The allocated time for this task is 2 days.

The start date of this task is 13 September 2023, and the end date is 14 September 2023.

The owner of the task is Tan Yu.

The status of the task is "Completed."

The priority of the task is **high**.

**Comment by NekoCoaster** [comment]
Completed. Ready for review.

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by hexluna** [comment]
Reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by minvee** [comment]
Reviewed

**Comment by NekoCoaster** [comment]
Closed as completed.
