### ISSUE TITLE
1.3.4.2 Safety and Security Requirements

### ISSUE THREAD

**Issue by NekoCoaster** [SujanRaj20/INF2001-P4-3#24]
Task ID: #24

The Task is about specifying requirements related to safety, security, and privacy considerations associated with the use of the product. This includes identifying potential risks of loss, damage, or harm that could result from product usage and defining measures to mitigate these risks. Additionally, it involves addressing security and privacy concerns, adhering to relevant external policies and regulations, and defining any necessary safety certifications.

The goal is to establish a clear set of safety and security requirements that ensure the product is designed and used in a manner that minimizes risks and protects data and users. These requirements should encompass encryption standards, multi-factor authentication, and other security measures that align with the client's needs and any relevant regulations.

The completion criteria are met when a comprehensive list of safety and security requirements is provided, each with a clear description and rationale. These requirements should cover data encryption, user authentication, and other safety and security measures, ensuring the product meets the necessary standards.

The allocated time for this task is 2 days.

The start date of this task is 14 September 2023, and the end date is 15 September 2023.

The owner of the task is Vivian Seah.

The status of the task is "Completed."

The priority of the task is **high**.

**Comment by NekoCoaster** [comment]
TODO:  Provide safety/security requirements based on your interview with the client - again you may need to be somewhat creative here.  At the least, you should have some security for the mobile connection.

**NFR5:** Data transmitted from and received are always encrypted with AES-128.
**NFR6:** All approving roles must use a different factor of authentication from the user authentications (on top of 2FA) for approval processes.

**Comment by minvee** [comment]
Completed, Ready for review

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by hexluna** [comment]
Reviewed

**Comment by NekoCoaster** [comment]
Reviewed.

**Comment by NekoCoaster** [comment]
Closed as completed.
