### ISSUE TITLE
1.4.2 Project Management.

### ISSUE THREAD

**Issue by NekoCoaster** [SujanRaj20/INF2001-P4-3#26]
Task ID: #26

The Task is about creating a project management Gantt Chart with a Work Breakdown Structure (WBS) and any required charts such as Burndown charts. This task involves planning and visualizing project tasks and timelines without the need to include the detailed calculations used for the WBS.

The goal is to develop a clear and organized project management chart that provides a visual representation of task dependencies, durations, and milestones.

The completion criteria is the successful creation of the Gantt Chart with all necessary components and information.

The allocated time is 3 days.

The start date of this task is 18 September 2023, and the end date is 20 September 2023.

The owner of the task is Amabel Lim Zi Qin.

The status of the task is "Completed".

The priority of the task is **high**.

**Comment by Amabellzq** [comment]
Completed, Ready for review

**Comment by hexluna** [comment]
Reviewed

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by minvee** [comment]
reviewed

**Comment by NekoCoaster** [comment]
Reviewed.

**Comment by NekoCoaster** [comment]
Closed as completed.
