### ISSUE TITLE
1.5 Appendix A – Use Case Descriptions

### ISSUE THREAD

**Issue by NekoCoaster** [SujanRaj20/INF2001-P4-3#27]
Task ID: #27

The Task is about creating a table of use case descriptions as outlined in the provided format. This task involves documenting essential information for various use cases, including Use Case ID, Use Case Name, Description, Primary Actor, Pre-conditions, Post-conditions, Main Success Scenarios, and Alternative Scenarios.

The goal is to compile a comprehensive and well-structured document containing use case descriptions that can be used for reference in project development and management. Each use case should be clearly defined and organized within the table.

The completion criteria for this task include the successful creation of the table with all specified use case details accurately filled in according to the provided format.

The allocated time for this task is 4 days.

The start date of this task is 19 September 2023, and the end date is 22 September 2023.

The owner of the task is Everyone.

The status of the task is "Completed".

The priority of the task is **high**.

**Comment by NekoCoaster** [comment]
Completed. Ready for review.

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by hexluna** [comment]
Reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by minvee** [comment]
reviewed

**Comment by NekoCoaster** [comment]
Closed as completed.
