### ISSUE TITLE
2.1.1 Update Use Case Descriptions

### ISSUE THREAD

**Issue by ColdRainyDay365** [SujanRaj20/INF2001-P4-3#32]
Task ID: #5.0

Task Description: The task involves revising and updating the use case descriptions based on the feedback received on the M1 report. The aim is to incorporate changes, improvements, feedbacks to ensure accurate and comprehensive use case descriptions.

Allocated Time: 3 days

Start Date: 17 October 2023

End Date: 20 October 2023

Owner: Sujan

Task Status: Completed

Priority: Medium

Details: This task focuses on revising the use case descriptions based on feedback provided in the M1 report. The exact nature of the feedback, as well as the specific changes or enhancements required, should be documented and addressed in the revised use case description. This task is expected to be completed within a 3-day timeframe, starting on 17th October and ending on 20th October. Sujan is the assigned owner responsible for this task, and its priority is considered medium.

**Comment by JasonICTSE** [comment]
updated use case descriptions for Manage Job Assignments 
- Make changes to description: 9. The system displays a message indicating acceptance or rejection of job assignment. 

- Add alt flow: 3a2 pilot acknowledges message displayed by the system 3a3 pilot is redirected to the landing page

**Comment by ColdRainyDay365** [comment]
The following changes have been made to the use case descriptions


1) For usecase description 5, the use case name was changed to Manage qualifications and training status to better reflect the scope of the use case description.

2) For usecase description 1, the use case description was edited to differentiate between notifications, and cleaned up the incomplete alternate flow

Please review and comment if ok?

**Comment by hexluna** [comment]
The following changes have been made to the use case descriptions:

i. Changed name of Manage training to Manage qualification and training status.

**Comment by Amabellzq** [comment]
Reviewed

**Comment by NekoCoaster** [comment]
Use case description reviewed.

**Comment by hexluna** [comment]
Reviewed

**Comment by minvee** [comment]
Reviewed

**Comment by ColdRainyDay365** [comment]
Closed as completed
