### ISSUE TITLE
2.1.3 Gantt Chart Revision for M2 and M3

### ISSUE THREAD

**Issue by Amabellzq** [SujanRaj20/INF2001-P4-3#33]
Task ID: 2.1.3

Task Description: The task is to update the exisitng Gantt chart according to the project's requirements and scope. 

Allocated Time: 3 days

Start Date: 19 October 2023

End Date: 27 October 2023

Owner: Amabel

Task Status: Pending

Priority: Medium

Details: This task focuses on creating a clear overview for the team to have a gauge of when the specific tasks need to be completed and closed according to the cases opened in github.

**Comment by Amabellzq** [comment]
Gantt Chart Revision revision to be reviewed

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by hexluna** [comment]
reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by minvee** [comment]
Reviewed

**Comment by NekoCoaster** [comment]
Reviewed
