### ISSUE TITLE
2.1.2 Update Use Case Diagram

### ISSUE THREAD

**Issue by JasonICTSE** [SujanRaj20/INF2001-P4-3#34]
Task ID: 2.1.2

Task Description: The task involves revising and updating the use case diagram based on the feedback received on the M1 report. The aim is to incorporate changes, improvements, or new functionalities to ensure accurate and comprehensive documentation.

Allocated Time: 3 days

Start Date: 20 October 2023

End Date: 23 October 2023

Owner: Jason

Task Status: Completed

Priority: Medium

Details: This task focuses on revising the use case diagram based on feedback provided in the M1 report. The exact nature of the feedback, as well as the specific changes or enhancements required, should be documented and addressed in the revised use case diagram. This task is expected to be completed within a 3-day timeframe, starting on 20th October and ending on 23rd October. Jason is the assigned owner responsible for this task, and its priority is considered medium.

The use case diagram should accurately reflect the updated requirements and functionalities discussed in the M1 report.

**Comment by hexluna** [comment]
The following changes have been made to the use case diagram

i. Added Database actor to use case diagram

**Comment by JasonICTSE** [comment]
The following changes have been made to the use case diagram

i. Change manage training status to manage qualifications and training status

**Comment by NekoCoaster** [comment]
Use case diagram update reviewed.

**Comment by Amabellzq** [comment]
use case diagram reviewed

**Comment by ColdRainyDay365** [comment]
use case diagram reviewed.

**Comment by hexluna** [comment]
use case diagram reviewed

**Comment by minvee** [comment]
Use Case Diagram Reviewed

**Comment by JasonICTSE** [comment]
Closed as completed
