### ISSUE TITLE
2.3.0 Allocate Jobs for Manager - Sequence Diagram

### ISSUE THREAD

**Issue by minvee** [SujanRaj20/INF2001-P4-3#35]
Task ID: 2.4.1

The Task is to present a sequence diagram to elucidate the flow of our use case for the manager use case "Allocate Jobs". With this diagram, it offers a visual representation of the step-by-step interactions between pilots and the job assignments in the use case, providing a comprehensive understanding of the process.

The goal is to create a clear overview of the Manger interaction with the interface to accept and reject job assignments as one of the key functionalities of the system. At the same time, integrating the use cases of the manager role to view and allocate jobs to pilots one week at a time on the user-interface called job allocation. 

The allocated time for this task is 7 days.

The start date of this task is 20 October 2023, and the end date is 27 October 2023.

The owner of the task is Vivian.

The status of the task is Pending.

The priority of the task is Medium.

**Comment by minvee** [comment]
Job allocation sequence diagram for Manager to be reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by hexluna** [comment]
Reviewed

**Comment by NekoCoaster** [comment]
Reviewed

**Comment by ColdRainyDay365** [comment]
Reviewed

**Comment by minvee** [comment]
Closed as completed.
