### ISSUE TITLE
2.2.0 Create class diagrams

### ISSUE THREAD

**Issue by Amabellzq** [SujanRaj20/INF2001-P4-3#36]
Task ID: 2.2

Task Description: The Task is to identify relationship between classes, capture system structure, model object-oriented concept and show class relationships in a diagram that should depict the relationship between classes, associations, inheritance and dependencies

Allocated Time: 10 days

Start Date: 18 October 2023

End Date: 27 October 2023

Owner: Amabel

Task Status: Pending

Priority: Medium

Details: This task focuses on the representing the structure and relationships of classes and objects within a software system. The tasks was actually already begin before 23 October after we have received the feedback from our M1 report and has to be arranged till 27 October as there are changes to be made throughout the period. 

The class diagram should accurately reflect the updated requirements and functionalities discussed in the M2 report.

**Comment by Amabellzq** [comment]
Class diagram to be reviewed

**Comment by JasonICTSE** [comment]
The following changes has been made.
Added entity classes with relationships.
Added Boundary classes methods.
Added entity classes getters and setters as well as datatype for method calls

**Comment by ColdRainyDay365** [comment]
The following changes were made

Added control class, methods
Added interfaces
Added one to one/many relationship for entity classes with aggregation or composition
Refined & standardise the arrows, relationships

**Comment by NekoCoaster** [comment]
The following changes have been made:
Updated and edited methods for entities
Standardized and refined methods for entities and control classes.

**Comment by hexluna** [comment]
The following changes has been made
Added control class methods
Added interface methods

**Comment by minvee** [comment]
The following changes has been made:
=> Added control class methods
=> Added interface methods
