### ISSUE TITLE
2.3.1 Manage Job Assignment for Pilots - Sequence Diagram

### ISSUE THREAD

**Issue by NekoCoaster** [SujanRaj20/INF2001-P4-3#37]
Task ID: 2.4.2

The task is to present a sequence diagram to demonstrate the communication flow between different components in our system for the pilot's use case "Managing Job Assignments". This diagram aims to offer a visual representation of the step-by-step interactions between the pilots and the system under the use case "Managing Job Assignments" to provide a comprehensive understanding of the process.

The goal of this task is to create a clear overview of the pilot's interaction with the interface to accept and/or reject any job assignments that have been given to the pilot. This task aims to demonstrate the 3 different use case of: Accepting, Rejecting and in the event of no job assignments found.

The allocated time for this task is 7 days.

The start date of this task is 20 October 2023, and the end date is 27 October 2023.

The owner of the task is Tan Yu.

The status of the task is Pending.

The priority of the task is Medium.

**Comment by NekoCoaster** [comment]
"Manage Job Assignment for Pilots - Sequence Diagram" to be reviewed

**Comment by hexluna** [comment]
The following changes has been made:

Created and linked alternate flow 8a and 10a for Manage Job Assignment sequence diagram

**Comment by Amabellzq** [comment]
The following changes has been made.

Created some methods for the JobAssignmentUI boundary class as well as the SQL query towards to the database

**Comment by JasonICTSE** [comment]
reviewed

**Comment by hexluna** [comment]
Reviewed

**Comment by minvee** [comment]
Reviewed

**Comment by ColdRainyDay365** [comment]
reviewed
