### ISSUE TITLE
2.1 Updating users requirements

### ISSUE THREAD

**Issue by hexluna** [SujanRaj20/INF2001-P4-3#38]
Task ID 2.1:

The Task is to update the requirements section of our M1 report to M2 so as to suit the guidelines of the project plan.

The goal is to provide the client a clearer understanding and view about our project's goals and requirements.

The allocated time for this task is 6 days.

The start date of this task is 23 October 2023, and the end date is 28 October 2023.

The owner of the task is Ying Ee.

The status of the task is Completed.

The priority of the task is medium.

**Comment by hexluna** [comment]
User requirements has been updated:

The use case model has been updated with an additional Database actor

Added FR : The system shall allow the manager to manage training and licenses of the pilot on Manage training and license status page
 
NFR11 Old: Data backup and server recovery 
The system is required to conduct automated data backups on a daily basis to mitigate the risk of data loss. Additionally, a comprehensive disaster recovery plan must be in place to facilitate data and system functionality restoration in the event of system failures.


NFR11 New: Sensitive information of the user shall be encrypted with SHA256 in database

NFR12 Old: User authentication
Mandatory user authentication is necessary for system access.
User identities will undergo two-factor authentication (2FA) using OTP (One-Time Password) to enhance security.


NFR12 New: Account can only be created by IT Administrator

Added and changed sequence in Manage Job Assignment Use Case Description

Renamed Use Case Description M-UC5 name from Manage training status to Manage license and training status 

Updated additional description to Use Case Description M-UC7 View Availability

Updated alternative flow sequence in Use Case Description M-UC9 Allocate Jobs

**Comment by hexluna** [comment]
To be reviewed.

**Comment by NekoCoaster** [comment]
Reviewed

**Comment by JasonICTSE** [comment]
Reviewed

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by minvee** [comment]
reviewed

**Comment by hexluna** [comment]
Completed,closed
