### ISSUE TITLE
2.4.0 Create component diagrams

### ISSUE THREAD

**Issue by Amabellzq** [SujanRaj20/INF2001-P4-3#39]
Task ID: 2.4.3

Task Description: The Task is to create a component diagram that visually represents the integration of specific project components to demonstrate how they collectively form a unified design.

Allocated Time: 3 days

Start Date: 25 October 2023

End Date: 28 October 2023

Owner: Amabel

Task Status: Completed

Priority: High

Details: This task focuses on creating a project understanding and communication by visualising the relationships and dependencies between individual components, ensuring a coherent and holistic project design.The tasks was assigned later as we wants to ensure that the class diagrams is finalised before creating the components diagram.  

The component diagrams should accurately reflect the requirements and functionalities discussed in the M1 and M2 report.

**Comment by Amabellzq** [comment]
completed to be reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by NekoCoaster** [comment]
Reviewed

**Comment by hexluna** [comment]
reviewed

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by minvee** [comment]
reviewed
