### ISSUE TITLE
3.3.1 Implement Control Flow Graph

### ISSUE THREAD

**Issue by ColdRainyDay365** [SujanRaj20/INF2001-P4-3#41]
Task ID: 3.3.1

Task Description: Implement a control flow graph where nodes represent basic blocks and edges represent the possible flow of control between blocks. The CFG is a visual representation that outlines the control flow and logic within the code, including decision points, branches, loops, and function calls. Key responsibilities include analyzing the code's structure, constructing the CFG, and ensuring it accurately reflects the code's control flow. This graphical representation serves as a crucial tool for understanding and assessing the code's behavior and is instrumental in designing test cases for thorough white box testing.

Allocated Time: 19 days

Start Date: 7 November 2023

End Date: 25 November 2023

Owner:To be edited 

Task Status: In Progress

Priority: Medium

Details: This task involves the creation of a Control Flow Graph (CFG) for a software module or application. The graph is annotated with labels to signify code segments and conditions, aiding in code comprehension. This graphical representation is instrumental in white box testing, helping testers design comprehensive test cases and understand the code's behavior, contributing to improved software quality and reliability. Thorough documentation of the CFG ensures its usability for reference in testing and quality assurance efforts.

**Comment by ColdRainyDay365** [comment]
Completed. Pending peer review.

**Comment by NekoCoaster** [comment]
Reviewed

**Comment by hexluna** [comment]
reviewed

**Comment by minvee** [comment]
reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by ColdRainyDay365** [comment]
closed as completed
