### ISSUE TITLE
3.3.0 White Box Testing

### ISSUE THREAD

**Issue by ColdRainyDay365** [SujanRaj20/INF2001-P4-3#42]
Task ID: 3.3.0

Task Description: In this task, we will perform white box testing on a suitably complex method with at least 10 lines of code and two decision points. This method should be different from the one selected for the pseudocode. The task involves writing pseudocode for the selected method, constructing the Control Flow Graph (CFG) to visualize its structure

Allocated Time: 19 days

Start Date: 7 November 2023

End Date: 25 November 2023

Owner:To be edited 

Task Status: In Progress

Priority: Medium

Details: This task's objective is to thoroughly assess the selected method, ensuring that it behaves as intended and identifying potential errors or inconsistencies. This comprehensive approach ensures thorough testing and contributes to the overall reliability and quality of the software.

**Comment by ColdRainyDay365** [comment]
Completed. Pending peer review.

**Comment by NekoCoaster** [comment]
Reviewed

**Comment by hexluna** [comment]
reviewed

**Comment by minvee** [comment]
reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by ColdRainyDay365** [comment]
closed as completed
