### ISSUE TITLE
3.1.3 Create prototype for Pilots

### ISSUE THREAD

**Issue by Amabellzq** [SujanRaj20/INF2001-P4-3#43]
Task ID: 3.1.3

Task Description: This task focuses on the development of a functional prototype for the Pilot Workload Management System, offering a tangible and interactive representation of the system's core features and user interface. It serves as a dynamic tool for collaboration, ensuring that the final Pilot Workload Management System meets the unique requirements and expectations of aviation professionals.

Allocated Time: 19 days

Start Date: 7 November 2023

End Date: 25 November 2023

Owner: to be edited

Task Status: In Progress

Priority: High

Details: This prototype serves as a functional representation of the final system, offering a preview of core features and user interfaces. It facilitates direct engagement with pilots and managers, enabling feedback and validation. Key responsibilities include translating system requirements into the prototype, integrating pilot-specific functionalities. this is a dynamic tool for collaboration, ensuring that the system aligns with the operational needs and preferences of pilots in the aviation industry.

**Comment by Amabellzq** [comment]
Completed. Pending peer review

**Comment by hexluna** [comment]
reviewed

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by NekoCoaster** [comment]
Reviewed.

**Comment by minvee** [comment]
Reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by Amabellzq** [comment]
completed and closed
