### ISSUE TITLE
3.1.2 Create a prototype for Managers

### ISSUE THREAD

**Issue by minvee** [SujanRaj20/INF2001-P4-3#44]
Task ID: 3.1.2

Task Description: Creation of a prototype aimed at providing managers with a tangible and interactive representation of a proposed system or feature. The prototype serves as a visual and functional model, offering a preview of the final product's user interface, functionality, and user experience. Key responsibilities include translating conceptual ideas into a working prototype, incorporating manager-specific features and feedback, and ensuring that the prototype aligns with the project's objectives.

Allocated Time: 6 days

Start Date: 12 November 2023

End Date: 25 November 2023

Owner: Vivian Seah

Task Status: Completed

Priority: High

Details: Tasks involves the creation of an interactive model to cater to managers' specific needs. This prototype, generated through collaborative efforts, translates conceptual ideas into a functional representation of the final system or feature. It integrates manager-specific features and feedback, aligning with project objectives. The task encompasses requirements review, feedback incorporation, usability testing, and iterative refinement, ensuring that the prototype evolves in response to pilot's input. It empowers managers to make informed decisions about pilot's schedule and preferences.

**Comment by minvee** [comment]
Completed. Pending peer review.

**Comment by hexluna** [comment]
reviewed

**Comment by ColdRainyDay365** [comment]
Reviewed

**Comment by NekoCoaster** [comment]
Reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by minvee** [comment]
closed as completed
