### ISSUE TITLE
3.3.2 Calculate Cyclomatic Complexity

### ISSUE THREAD

**Issue by minvee** [SujanRaj20/INF2001-P4-3#45]
Task ID: 3.3.2

Task Description: This task involves determining the cyclomatic complexity of a software module or application as part of white box testing. Cyclomatic complexity is a quantitative measure used to assess the structural complexity of code, helping to identify potential issues and guide test case design. The resulting complexity value aids in understanding the code's testability and can be used to develop an effective test strategy to ensure thorough test coverage.

Allocated Time: 19 days

Start Date: 7 November 2023

End Date: 25 November 2023

Owner: Ying Ee

Task Status: In Progress

Priority: Medium

Details: Calculating complexity in white box testing involves assessing the structural intricacy of software code to understand its testability and potential challenges. It typically includes identifying decision points, loops, and branches within the code that affect its control flow. The calculated complexity value provides a quantitative measure of code intricacy, aiding in test case design and strategy development. It helps testers focus their efforts on areas of code that are more complex, ensuring thorough test coverage and improved software quality. The result of complexity calculation is a valuable metric that guides white box testing, ultimately leading to more robust and reliable software.

**Comment by hexluna** [comment]
completed, pending peer review

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by NekoCoaster** [comment]
Reviewed.

**Comment by minvee** [comment]
reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by hexluna** [comment]
completed and closed
