### ISSUE TITLE
3.2.0 Black Box Testing

### ISSUE THREAD

**Issue by hexluna** [SujanRaj20/INF2001-P4-3#46]
Task ID: 3.2.0

Task Description: In this task, the focus is on designing a Decision Table Black Box Testing for one of the prominent methods related to the specified use cases. The approach involves creating a decision table that systematically covers various input combinations and their expected outcomes. The decision table aids in testing the method's behavior under different conditions, ensuring comprehensive test coverage. The resulting test cases will help verify that the method performs as expected across a range of scenarios.

Allocated Time: 19 days

Start Date: 7 November 2023

End Date: 25 November 2023

Owner: Tan Yu

Task Status: In Progress

Priority: Medium

Details: Involves selecting a critical method within a software application and systematically testing its behavior under various input conditions. It begins with identifying input factors, specifying their possible values, and creating a decision table to map combinations of these factors to expected outcomes. Test cases are then generated based on the decision table, allowing for thorough testing of the method's functionality. This approach ensures the robustness and accuracy of the method in different scenarios, contributing to the overall quality and reliability of the software.

**Comment by NekoCoaster** [comment]
Completed. Pending peer review.

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by hexluna** [comment]
reviewed

**Comment by minvee** [comment]
Reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by NekoCoaster** [comment]
Completed and Closed.
