### ISSUE TITLE
3.2.1 Design Decision Tables

### ISSUE THREAD

**Issue by hexluna** [SujanRaj20/INF2001-P4-3#47]
Task ID: 3.2.1

Task Description: Decision tables are structured matrices used to systematically test various combinations of input conditions and their corresponding expected outcomes.  Designing decision tables is essential for ensuring that software functions accurately and reliably under different conditions and user inputs.

Allocated Time: 19 days

Start Date: 7 November 2023

End Date: 25 November 2023

Owner: Ying Ee

Task Status: In Progress

Priority: Medium

Details: Tables provide a clear framework for testing various combinations of inputs and help ensure comprehensive test coverage. The process includes identifying input conditions, defining their possible values, constructing the decision table, generating test cases based on the table, and executing tests to evaluate the software's behavior. Effective documentation is crucial for tracking the testing process and results, contributing to the overall reliability and quality of software applications. Decision tables are valuable tools for systematically assessing software under different scenarios and user inputs.

**Comment by hexluna** [comment]
Completed ,pending peer review.

**Comment by NekoCoaster** [comment]
Reviewed.

**Comment by ColdRainyDay365** [comment]
Reviewed

**Comment by minvee** [comment]
reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by hexluna** [comment]
completed and closed
