### ISSUE TITLE
3.1.4 Create prototype for IT administrator

### ISSUE THREAD

**Issue by NekoCoaster** [SujanRaj20/INF2001-P4-3#48]
Task ID: 3.1.4

Task Description: This task focuses on developing a functional prototype for IT administrators, specifically targeting account creation and deletion features for managers and pilots within the Pilot Workload Management System. The prototype provides a hands-on preview of the user interface and functionality related to account management.

Allocated Time: 19 days

Start Date: 7 November 2023

End Date: 25 November 2023

Owner: Tan Yu
Task Status: In Progress 

Priority: High

Details: This task involves the creation of a functional prototype focused on account creation and deletion features for both managers and pilots, providing IT administrators with a visual and interactive model. This prototype offers a hands-on preview of the user interface and functionalities related to account management. Ensuring that IT administrators have effective tools for efficiently managing user accounts, contributing to an efficient and user-friendly system for managers and pilots within the Pilot's Workload Management System.

**Comment by NekoCoaster** [comment]
Completed. Pending Peer Review.

**Comment by ColdRainyDay365** [comment]
reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by hexluna** [comment]
reviewed

**Comment by minvee** [comment]
Reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by NekoCoaster** [comment]
Completed and Closed.
