### ISSUE TITLE
3.3.3 Conduct Basic Path Testing

### ISSUE THREAD

**Issue by minvee** [SujanRaj20/INF2001-P4-3#49]
Task ID: 3.3.3

Task Description: This task involves performing basic path testing as part of white box testing to assess the control flow of a software application. Basic path testing is a systematic technique that focuses on testing various paths or routes through the code, ensuring that each path is executed and validated. Key responsibilities include identifying distinct paths in the code, designing test cases to cover each path, executing the tests, and assessing the behavior of the software. 

Allocated Time: 6 days

Start Date: 12 November 2023

End Date: 25 November 2023

Owner: Vivian Seah

Task Status: Completed

Priority: Medium

Details: By testing the various routes within the code, basic path testing helps uncover logic errors, flow issues, and potential bugs, ultimately enhancing the software's quality, reliability, and robustness. It is an essential step in white box testing to ensure comprehensive coverage and minimize the risk of undetected defects.

**Comment by minvee** [comment]
Completed. Pending peer review.

**Comment by ColdRainyDay365** [comment]
Reviewed

**Comment by NekoCoaster** [comment]
Reviewed.

**Comment by hexluna** [comment]
reviewed

**Comment by JasonICTSE** [comment]
reviewed

**Comment by Amabellzq** [comment]
reviewed

**Comment by minvee** [comment]
closed as completed
